FROM node:20-alpine AS deps

WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM deps AS build

WORKDIR /app
COPY . .
RUN npm run build
RUN mkdir -p dist/data && cp -R src/data dist/

FROM node:20-alpine AS prod

WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist ./dist
COPY --from=build /app/.env ./
RUN npm prune --omit=dev

EXPOSE 3000

CMD ["node", "dist/index.js"]
